theme: jekyll-theme-architect


<html>
  <title>
    Vraj's Yelp
  </title>

  <head>
    <hi style = "font-family:Brush Script MT;font-size:35px;font-style:italic;">
         <u>Welcome to Vraj's Yelp</u>
  </hi>
</head>

  <style>
    body {
      background-color:maroon;
      color:#fff;
      text-align:center;
    }

  </style>
  <!-- Load icon library -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- The form -->
  <form class="example" action="action_page.php">
    <input type="text" placeholder="Search by Restuarant..." name="search">
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>

  <!-- The form -->
  <form class="example" action="action_page.php">
    <input type="text" placeholder="Search by Price..." name="search">
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>

  <!-- The form -->
  <form class="example" action="action_page.php">
    <input type="text" placeholder="Search by Rating..." name="search">
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>

</html>
